/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainJFrame.java
 *
 * Created on Sep 28, 2012, 11:21:25 PM
 */

package UserInterface;


import Business.TravelAgency;
import UserInterface.Airliners.AirlinersMainJPanel;
import UserInterface.Customers.CustomerMainJPanel;
import java.awt.CardLayout;

/**
 *
 * @author Rushabh
 */
public class MainJFrame extends javax.swing.JFrame {

    private TravelAgency travelAgency;
//    private MasterOrderCatalog moc;
    
    /** Creates new form MainJFrame */
    public MainJFrame() {
        initComponents();
        this.travelAgency = new TravelAgency();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        mainControl = new javax.swing.JPanel();
        customerBtn = new javax.swing.JButton();
        airlinersBtn = new javax.swing.JButton();
        travelAgencyBtn = new javax.swing.JButton();
        mainContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jSplitPane1.setDividerLocation(150);

        mainControl.setPreferredSize(new java.awt.Dimension(200, 600));

        customerBtn.setText("Customers");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        airlinersBtn.setText("Airliner");
        airlinersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinersBtnActionPerformed(evt);
            }
        });

        travelAgencyBtn.setText("Travel Agency");
        travelAgencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelAgencyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainControlLayout = new javax.swing.GroupLayout(mainControl);
        mainControl.setLayout(mainControlLayout);
        mainControlLayout.setHorizontalGroup(
            mainControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(travelAgencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(airlinersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        mainControlLayout.setVerticalGroup(
            mainControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainControlLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(airlinersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(travelAgencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(mainControl);

        mainContainer.setPreferredSize(new java.awt.Dimension(700, 600));
        mainContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(mainContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        CustomerMainJPanel panel = new CustomerMainJPanel(mainContainer, travelAgency);
        mainContainer.add("CustomerMainJPanel",panel);
        CardLayout layout = (CardLayout)mainContainer.getLayout();
        layout.next(mainContainer);
    }//GEN-LAST:event_customerBtnActionPerformed

    private void airlinersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinersBtnActionPerformed
        // TODO add your handling code here:
        AirlinersMainJPanel panel = new AirlinersMainJPanel(mainContainer, travelAgency);
        mainContainer.add("AirlinersMainJPanel",panel);
        CardLayout layout = (CardLayout)mainContainer.getLayout();
        layout.next(mainContainer);
    }//GEN-LAST:event_airlinersBtnActionPerformed

    private void travelAgencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelAgencyBtnActionPerformed
        // TODO add your handling code here:
       TravelAgencyJPanel panel = new TravelAgencyJPanel(mainContainer, travelAgency);
        mainContainer.add("TravelAgencyJPanel",panel);
        CardLayout layout = (CardLayout)mainContainer.getLayout();
        layout.next(mainContainer);
    }//GEN-LAST:event_travelAgencyBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airlinersBtn;
    private javax.swing.JButton customerBtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel mainControl;
    private javax.swing.JButton travelAgencyBtn;
    // End of variables declaration//GEN-END:variables

}
