/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.TravelAgency;
import UserInterface.Airliners.ManageAirlinersJPanel;
import UserInterface.Customers.CustomerMainJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Richard
 */
public class TravelAgencyJPanel extends javax.swing.JPanel {

     private JPanel mainContainer;
    private TravelAgency travelAgency;

    TravelAgencyJPanel(JPanel mainContainer, TravelAgency travelAgency) {
       initComponents();
        mainContainer = mainContainer;
        this.travelAgency =travelAgency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackBtn = new javax.swing.JButton();
        searchBtn2 = new javax.swing.JButton();
        manageAirlinerBtn2 = new javax.swing.JButton();

        BackBtn.setText("<< Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        searchBtn2.setText("Customer");
        searchBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn2ActionPerformed(evt);
            }
        });

        manageAirlinerBtn2.setText("Airliners");
        manageAirlinerBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirlinerBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageAirlinerBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(manageAirlinerBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(searchBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        mainContainer.remove(this);
        CardLayout layout = (CardLayout)mainContainer.getLayout();
        layout.previous(mainContainer);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void searchBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn2ActionPerformed
        // TODO add your handling code here:
        CustomerMainJPanel panel = new CustomerMainJPanel(mainContainer, travelAgency);
        mainContainer.add("CustomerMainJPanel", panel);
        CardLayout layout = (CardLayout)mainContainer.getLayout();
        layout.next(mainContainer);
    }//GEN-LAST:event_searchBtn2ActionPerformed

    private void manageAirlinerBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirlinerBtn2ActionPerformed
        // TODO add your handling code here:
        ManageAirlinersJPanel panel = new ManageAirlinersJPanel(mainContainer, travelAgency);
        mainContainer.add("2ManageAirlinersJPanel", panel);
        CardLayout layout = (CardLayout)mainContainer.getLayout();
        layout.next(mainContainer);
    }//GEN-LAST:event_manageAirlinerBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton manageAirlinerBtn2;
    private javax.swing.JButton searchBtn2;
    // End of variables declaration//GEN-END:variables
}
