/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.License;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author liuyi
 */
public class CreateDriverLicenseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DriverLicenseJPanel
     */
    private License license;
    static String path;
    public CreateDriverLicenseJPanel( License license) {
        initComponents();
        this.license=license;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        LicensenumTxtField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        IssuedTxtField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ExpirationTxtField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        BloodtypeTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CreateLicenseBtn = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        UploadPicBtn = new javax.swing.JButton();
        picUpLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(249, 254, 254));
        setPreferredSize(new java.awt.Dimension(1010, 1166));

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setText("License number:");

        LicensenumTxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        LicensenumTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicensenumTxtFieldActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("Date it was issued:");

        IssuedTxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        IssuedTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuedTxtFieldActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 102));
        jLabel25.setText("Date of expiration:");

        ExpirationTxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        ExpirationTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpirationTxtFieldActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("blood type:");

        BloodtypeTxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        BloodtypeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodtypeTxtFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setText("Driver License Information");

        CreateLicenseBtn.setBackground(new java.awt.Color(249, 254, 254));
        CreateLicenseBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        CreateLicenseBtn.setForeground(new java.awt.Color(0, 153, 153));
        CreateLicenseBtn.setText("Create");
        CreateLicenseBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        CreateLicenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateLicenseBtnActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("Upload the picture");

        UploadPicBtn.setBackground(new java.awt.Color(249, 254, 254));
        UploadPicBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        UploadPicBtn.setForeground(new java.awt.Color(0, 153, 153));
        UploadPicBtn.setText("Upload");
        UploadPicBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        UploadPicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadPicBtnActionPerformed(evt);
            }
        });

        picUpLabel.setBackground(java.awt.Color.white);
        picUpLabel.setForeground(new java.awt.Color(255, 255, 255));
        picUpLabel.setText("picture");
        picUpLabel.setToolTipText("Picture");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel26))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BloodtypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IssuedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExpirationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LicensenumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel27)
                        .addGap(69, 69, 69)
                        .addComponent(UploadPicBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(picUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CreateLicenseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(391, 391, 391))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel9)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LicensenumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(IssuedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ExpirationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(BloodtypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UploadPicBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(picUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateLicenseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LicensenumTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicensenumTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicensenumTxtFieldActionPerformed

    private void IssuedTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuedTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IssuedTxtFieldActionPerformed

    private void ExpirationTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpirationTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpirationTxtFieldActionPerformed

    private void BloodtypeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodtypeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodtypeTxtFieldActionPerformed

    private void CreateLicenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateLicenseBtnActionPerformed
        // TODO add your handling code here:
        // binding user input to driver license
        license.setBloodtype(BloodtypeTxtField.getText());
        license.setExpiration(ExpirationTxtField.getText());
        license.setIssueddate(IssuedTxtField.getText());
        license.setLicensenum(LicensenumTxtField.getText());
        JOptionPane.showConfirmDialog(null,"Are you sure to create the driver license information?");
        JOptionPane.showMessageDialog(null,"Create driver license information successfully");
    }//GEN-LAST:event_CreateLicenseBtnActionPerformed

    private void UploadPicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadPicBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser img=new JFileChooser();
        img.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i=img.showOpenDialog(null);
        if(i==img.APPROVE_OPTION){
        path = img.getSelectedFile().getAbsolutePath();
        String name=img.getSelectedFile().getName();
        JOptionPane.showConfirmDialog(null,"当前文件路径"+path+"\n当前文件名:"+name);
        }
        else{
        JOptionPane.showConfirmDialog(null,"没有选中文件");
                }
        ImageIcon icon=new ImageIcon(path);
        icon.setImage(icon.getImage().getScaledInstance(450, 450, Image.SCALE_DEFAULT));
        picUpLabel.setIcon(icon);
        
        
    }//GEN-LAST:event_UploadPicBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BloodtypeTxtField;
    private javax.swing.JButton CreateLicenseBtn;
    private javax.swing.JTextField ExpirationTxtField;
    private javax.swing.JTextField IssuedTxtField;
    private javax.swing.JTextField LicensenumTxtField;
    private javax.swing.JButton UploadPicBtn;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel picUpLabel;
    // End of variables declaration//GEN-END:variables
}
