/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Address;
import Business.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author liuyi
 */
public class CreateAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddressJPanel
     */
 private Address address;
 private Person person;
    
    public CreateAddressJPanel(Address address) {
        initComponents();
        this.address=address;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CityTxtField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        StateTxtField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ZipcodeTxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        StreetTxtField = new javax.swing.JTextField();
        CreateAddressBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 254, 254));
        setPreferredSize(new java.awt.Dimension(1010, 1166));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Street address:");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("City:");

        CityTxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        CityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTxtFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("State:");

        StateTxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        StateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateTxtFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Zip code:");

        ZipcodeTxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        ZipcodeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipcodeTxtFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel13.setText("Address Information");

        StreetTxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        StreetTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetTxtFieldActionPerformed(evt);
            }
        });

        CreateAddressBtn.setBackground(new java.awt.Color(249, 254, 254));
        CreateAddressBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        CreateAddressBtn.setForeground(new java.awt.Color(0, 153, 153));
        CreateAddressBtn.setText("Create");
        CreateAddressBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        CreateAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAddressBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CityTxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(StreetTxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                    .addComponent(ZipcodeTxtField))
                                .addComponent(CreateAddressBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(StateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel13)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel13)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(StreetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(223, 223, 223)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(StateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ZipcodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(CreateAddressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTxtFieldActionPerformed

    private void StateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateTxtFieldActionPerformed

    private void ZipcodeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipcodeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipcodeTxtFieldActionPerformed

    private void StreetTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetTxtFieldActionPerformed

    private void CreateAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAddressBtnActionPerformed
        // TODO add your handling code here:
        //binding user input to address
        address.setCity(CityTxtField.getText());
        address.setState(StateTxtField.getText());
        address.setStreet(StreetTxtField.getText());       
        address.setZipcode(ZipcodeTxtField.getText());
        person.setAddress(address);
        JOptionPane.showConfirmDialog(null,"Are you sure to create the address information?","",HEIGHT);
        JOptionPane.showMessageDialog(null,"Create the address information successfully","CREATE",HEIGHT);

    }//GEN-LAST:event_CreateAddressBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CityTxtField;
    private javax.swing.JButton CreateAddressBtn;
    private javax.swing.JTextField StateTxtField;
    private javax.swing.JTextField StreetTxtField;
    private javax.swing.JTextField ZipcodeTxtField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
