/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Medical;
import javax.swing.JOptionPane;
/**
 *
 * @author liuyi
 */
public class CreateMedicalRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalRecordJPanel
     */
    private Medical medical;
    public CreateMedicalRecordJPanel(Medical medical) {
        initComponents();
        this.medical=medical;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        RecordTxtField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Alergy1TxtField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Alergy2TxtField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Alergy3TxtField = new javax.swing.JTextField();
        CreateMedicalBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 254, 254));
        setPreferredSize(new java.awt.Dimension(1010, 1166));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setText("Medical Record Information");

        RecordTxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        RecordTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordTxtFieldActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("Medical record number:");

        jLabel29.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText("Allergy 1:");

        Alergy1TxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        Alergy1TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy1TxtFieldActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setText("Allergy 2:");

        Alergy2TxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        Alergy2TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy2TxtFieldActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 102));
        jLabel31.setText("Alergy 3:");

        Alergy3TxtField.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        Alergy3TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy3TxtFieldActionPerformed(evt);
            }
        });

        CreateMedicalBtn.setBackground(new java.awt.Color(249, 254, 254));
        CreateMedicalBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        CreateMedicalBtn.setForeground(new java.awt.Color(0, 153, 153));
        CreateMedicalBtn.setText("Create");
        CreateMedicalBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        CreateMedicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateMedicalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(199, 199, 199))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(206, 206, 206)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alergy3TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Alergy2TxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                .addComponent(Alergy1TxtField)
                                .addComponent(RecordTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(CreateMedicalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel9)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel9)
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(RecordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(Alergy1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(Alergy2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alergy3TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(CreateMedicalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RecordTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecordTxtFieldActionPerformed

    private void Alergy1TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy1TxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy1TxtFieldActionPerformed

    private void Alergy2TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy2TxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy2TxtFieldActionPerformed

    private void Alergy3TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy3TxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy3TxtFieldActionPerformed

    private void CreateMedicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateMedicalBtnActionPerformed
        // TODO add your handling code here:
        // binding user input to the medical record
        medical.setAlergy1(Alergy1TxtField.getText());
        medical.setAlergy2(Alergy2TxtField.getText());
         medical.setAlergy3(Alergy3TxtField.getText());
         medical.setRecordNum(RecordTxtField.getText());
        JOptionPane.showConfirmDialog(null,"Are you sure to create the medical record information?");
        JOptionPane.showMessageDialog(null,"Create medical record information successfully");
    }//GEN-LAST:event_CreateMedicalBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alergy1TxtField;
    private javax.swing.JTextField Alergy2TxtField;
    private javax.swing.JTextField Alergy3TxtField;
    private javax.swing.JButton CreateMedicalBtn;
    private javax.swing.JTextField RecordTxtField;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
