/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import Business.Address;
import Business.CheckingAccount;
import Business.Demographic;
import Business.License;
import Business.Medical;
import Business.SavingAccount;



/**
 *
 * @author liuyi
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;
    Address address=new Address();
    CheckingAccount checkingaccount=new CheckingAccount();
    Demographic demographic=new Demographic();
    License license=new License();
    Medical medical=new Medical();
    SavingAccount savingaccount=new SavingAccount();
    
    public MainJFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        SplitJPane1 = new javax.swing.JSplitPane();
        ControlJPanel = new javax.swing.JPanel();
        DemographicCreateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DemographicViewBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AddressCreateBtn = new javax.swing.JButton();
        AddressViewBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SavingCreateBtn = new javax.swing.JButton();
        SavingViewBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CheckingCreateBtn = new javax.swing.JButton();
        CheckingViewBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LicenseCreateBtn = new javax.swing.JButton();
        LicenseViewBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        MedicalCreateBtn = new javax.swing.JButton();
        MedicalViewBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ViewAllBtn = new javax.swing.JButton();
        DisplayJPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("  Personal Information");

        ControlJPanel.setBackground(new java.awt.Color(249, 254, 254));
        ControlJPanel.setPreferredSize(new java.awt.Dimension(405, 1404));
        ControlJPanel.setRequestFocusEnabled(false);

        DemographicCreateBtn.setBackground(new java.awt.Color(153, 153, 153));
        DemographicCreateBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        DemographicCreateBtn.setText("Create");
        DemographicCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemographicCreateBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Checking Account Information");

        DemographicViewBtn.setBackground(new java.awt.Color(153, 153, 153));
        DemographicViewBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        DemographicViewBtn.setText("View");
        DemographicViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemographicViewBtnActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Address Information");

        AddressCreateBtn.setBackground(new java.awt.Color(153, 153, 153));
        AddressCreateBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        AddressCreateBtn.setText("Create");
        AddressCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressCreateBtnActionPerformed(evt);
            }
        });

        AddressViewBtn.setBackground(new java.awt.Color(153, 153, 153));
        AddressViewBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        AddressViewBtn.setText("View");
        AddressViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressViewBtnActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Demographic Information");

        SavingCreateBtn.setBackground(new java.awt.Color(153, 153, 153));
        SavingCreateBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        SavingCreateBtn.setText("Create");
        SavingCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingCreateBtnActionPerformed(evt);
            }
        });

        SavingViewBtn.setBackground(new java.awt.Color(153, 153, 153));
        SavingViewBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        SavingViewBtn.setText("View");
        SavingViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingViewBtnActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Saving Account Information");

        CheckingCreateBtn.setBackground(new java.awt.Color(153, 153, 153));
        CheckingCreateBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        CheckingCreateBtn.setText("Create");
        CheckingCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckingCreateBtnActionPerformed(evt);
            }
        });

        CheckingViewBtn.setBackground(new java.awt.Color(153, 153, 153));
        CheckingViewBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        CheckingViewBtn.setText("View");
        CheckingViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckingViewBtnActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Driver License Information");

        LicenseCreateBtn.setBackground(new java.awt.Color(153, 153, 153));
        LicenseCreateBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        LicenseCreateBtn.setText("Create");
        LicenseCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicenseCreateBtnActionPerformed(evt);
            }
        });

        LicenseViewBtn.setBackground(new java.awt.Color(153, 153, 153));
        LicenseViewBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        LicenseViewBtn.setText("View");
        LicenseViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicenseViewBtnActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Medical Record Information");

        MedicalCreateBtn.setBackground(new java.awt.Color(153, 153, 153));
        MedicalCreateBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        MedicalCreateBtn.setText("Create");
        MedicalCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalCreateBtnActionPerformed(evt);
            }
        });

        MedicalViewBtn.setBackground(new java.awt.Color(153, 153, 153));
        MedicalViewBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        MedicalViewBtn.setText("View");
        MedicalViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalViewBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("---------------------------------------------");

        jLabel8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("--------------------------------------------");

        jLabel9.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("---------------------------------------------");

        jLabel10.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("---------------------------------------------");

        jLabel11.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("---------------------------------------------");

        jLabel12.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("--------------------------------------------");

        ViewAllBtn.setBackground(new java.awt.Color(0, 102, 102));
        ViewAllBtn.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        ViewAllBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewAllBtn.setText("View All");
        ViewAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlJPanelLayout = new javax.swing.GroupLayout(ControlJPanel);
        ControlJPanel.setLayout(ControlJPanelLayout);
        ControlJPanelLayout.setHorizontalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DemographicViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DemographicCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(ViewAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MedicalViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MedicalCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(ControlJPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddressViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3))
                    .addComponent(jLabel8)
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SavingViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SavingCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CheckingViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckingCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LicenseViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LicenseCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlJPanelLayout.setVerticalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(DemographicCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(DemographicViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(AddressViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SavingCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(SavingViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckingCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(CheckingViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LicenseCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(LicenseViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedicalCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(MedicalViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        SplitJPane1.setLeftComponent(ControlJPanel);

        DisplayJPanel.setBackground(java.awt.Color.white);
        DisplayJPanel.setPreferredSize(new java.awt.Dimension(1010, 1166));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Welcome :)");

        javax.swing.GroupLayout DisplayJPanelLayout = new javax.swing.GroupLayout(DisplayJPanel);
        DisplayJPanel.setLayout(DisplayJPanelLayout);
        DisplayJPanelLayout.setHorizontalGroup(
            DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayJPanelLayout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(363, 363, 363))
        );
        DisplayJPanelLayout.setVerticalGroup(
            DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayJPanelLayout.createSequentialGroup()
                .addGap(629, 629, 629)
                .addComponent(jLabel13)
                .addContainerGap(717, Short.MAX_VALUE))
        );

        SplitJPane1.setRightComponent(DisplayJPanel);

        getContentPane().add(SplitJPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MedicalViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalViewBtnActionPerformed
        // TODO add your handling code here:
         ViewMedicalRecordJPanel viewMedicalRecordJPanel=new ViewMedicalRecordJPanel(medical);
         SplitJPane1.setRightComponent(viewMedicalRecordJPanel);
    }//GEN-LAST:event_MedicalViewBtnActionPerformed

    private void MedicalCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalCreateBtnActionPerformed
        // TODO add your handling code here:
         CreateMedicalRecordJPanel createMedicalRecordJPanel=new CreateMedicalRecordJPanel(medical);
         SplitJPane1.setRightComponent(createMedicalRecordJPanel);
    }//GEN-LAST:event_MedicalCreateBtnActionPerformed

    private void LicenseViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicenseViewBtnActionPerformed
        // TODO add your handling code here:
         ViewDriverLicenseJPanel viewDriverLicenseJPanel=new ViewDriverLicenseJPanel(license);
         SplitJPane1.setRightComponent(viewDriverLicenseJPanel);
    }//GEN-LAST:event_LicenseViewBtnActionPerformed

    private void LicenseCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicenseCreateBtnActionPerformed
        // TODO add your handling code here:
         CreateDriverLicenseJPanel createDriverLicenseJPanel=new CreateDriverLicenseJPanel(license);
         SplitJPane1.setRightComponent(createDriverLicenseJPanel);
    }//GEN-LAST:event_LicenseCreateBtnActionPerformed

    private void CheckingViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckingViewBtnActionPerformed
        // TODO add your handling code here:
         ViewCheckingAccountJPanel viewCheckingAccountJPanel=new ViewCheckingAccountJPanel(checkingaccount);
         SplitJPane1.setRightComponent(viewCheckingAccountJPanel);
    }//GEN-LAST:event_CheckingViewBtnActionPerformed

    private void CheckingCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckingCreateBtnActionPerformed
        // TODO add your handling code here:
         CreateCheckingAccountJPanel createCheckingAccountJPanel=new CreateCheckingAccountJPanel(checkingaccount);
         SplitJPane1.setRightComponent(createCheckingAccountJPanel);
    }//GEN-LAST:event_CheckingCreateBtnActionPerformed

    private void SavingViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingViewBtnActionPerformed
        // TODO add your handling code here:
        ViewSavingAccountJPanel viewSavingAccountJPanel=new ViewSavingAccountJPanel(savingaccount);
        SplitJPane1.setRightComponent(viewSavingAccountJPanel);
    }//GEN-LAST:event_SavingViewBtnActionPerformed

    private void SavingCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingCreateBtnActionPerformed
        // TODO add your handling code here:
        CreateSavingAccountJPanel createSavingAccountJPanel=new CreateSavingAccountJPanel(savingaccount);
        SplitJPane1.setRightComponent(createSavingAccountJPanel);
    }//GEN-LAST:event_SavingCreateBtnActionPerformed

    private void AddressViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressViewBtnActionPerformed
        // TODO add your handling code here:
        ViewAddressJPanel viewAddressJPanel=new ViewAddressJPanel(address);
        SplitJPane1.setRightComponent(viewAddressJPanel);
    }//GEN-LAST:event_AddressViewBtnActionPerformed

    private void AddressCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressCreateBtnActionPerformed
        // TODO add your handling code here:
         CreateAddressJPanel createAddressJPanel=new CreateAddressJPanel(address);
         SplitJPane1.setRightComponent(createAddressJPanel);
    }//GEN-LAST:event_AddressCreateBtnActionPerformed

    private void DemographicViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemographicViewBtnActionPerformed
        // TODO add your handling code here:
        ViewDemographicJPanel viewDemographicJPanel=new ViewDemographicJPanel(demographic);
        SplitJPane1.setRightComponent(viewDemographicJPanel);
    }//GEN-LAST:event_DemographicViewBtnActionPerformed

    private void DemographicCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemographicCreateBtnActionPerformed
        // TODO add your handling code here:
        CreateDemographicJPanel createDemographicJPanel=new CreateDemographicJPanel(demographic);
        SplitJPane1.setRightComponent(createDemographicJPanel);
        
    }//GEN-LAST:event_DemographicCreateBtnActionPerformed

    private void ViewAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllBtnActionPerformed
        // TODO add your handling code here:
        
      //  SplitJPane1.setRightComponent(viewAllJPanel);
      //ViewAllJFrame viewAllJFrame=new ViewAllJFrame();
;        ViewAllJPanel viewAllJPanel=new ViewAllJPanel(person);
      SplitJPane1.setRightComponent(viewAllJPanel);
    }//GEN-LAST:event_ViewAllBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddressCreateBtn;
    private javax.swing.JButton AddressViewBtn;
    private javax.swing.JButton CheckingCreateBtn;
    private javax.swing.JButton CheckingViewBtn;
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JButton DemographicCreateBtn;
    private javax.swing.JButton DemographicViewBtn;
    private javax.swing.JPanel DisplayJPanel;
    private javax.swing.JButton LicenseCreateBtn;
    private javax.swing.JButton LicenseViewBtn;
    private javax.swing.JButton MedicalCreateBtn;
    private javax.swing.JButton MedicalViewBtn;
    private javax.swing.JButton SavingCreateBtn;
    private javax.swing.JButton SavingViewBtn;
    private javax.swing.JSplitPane SplitJPane1;
    private javax.swing.JButton ViewAllBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
