/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Demographic;
/**
 *
 * @author liuyi
 */
public class ViewDemographicJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDemographicJPanel
     */

    public ViewDemographicJPanel(Demographic demographic) {
        initComponents();
        displayDemographic(demographic);
        
    }
  private void displayDemographic(Demographic demographic){
      String age=demographic.getAge();
      AgeTxtField.setText(age);
      AgeTxtField.setEnabled(false);
      String birthday=demographic.getDateofbirth();
      BirthdayTxtField.setText(birthday);
      BirthdayTxtField.setEnabled(false);
      String first=demographic.getFirstname();
      FirstnameTxtField.setText(first);
      FirstnameTxtField.setEnabled(false);
      String height=demographic.getHeight();
      HeightTxtField.setText(height);
      HeightTxtField.setEnabled(false);
      String last=demographic.getLastname();
      LastnameTxtField.setText(last);
      LastnameTxtField.setEnabled(false);
      String phone=demographic.getPhonenumber();
      PhonenumTxtField.setText(phone);
      PhonenumTxtField.setEnabled(false);
      String ssn=demographic.getSSN();
      SSNTxtField.setText(ssn);
      SSNTxtField.setEnabled(false);
      String weight=demographic.getWeight();
      WeightTxtField.setText(weight);
      WeightTxtField.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FirstnameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LastnameTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PhonenumTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BirthdayTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AgeTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        HeightTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        WeightTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SSNTxtField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1010, 1166));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setText("Demographic Information");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("First name:");

        FirstnameTxtField.setEditable(false);
        FirstnameTxtField.setBackground(new java.awt.Color(240, 240, 240));
        FirstnameTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        FirstnameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameTxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Last name:");

        LastnameTxtField.setBackground(new java.awt.Color(240, 240, 240));
        LastnameTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        LastnameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Phone number:");

        PhonenumTxtField.setBackground(new java.awt.Color(240, 240, 240));
        PhonenumTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        PhonenumTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonenumTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Date of birth:");

        BirthdayTxtField.setBackground(new java.awt.Color(240, 240, 240));
        BirthdayTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        BirthdayTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthdayTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Age:");

        AgeTxtField.setBackground(new java.awt.Color(240, 240, 240));
        AgeTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        AgeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTxtFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Height:");

        HeightTxtField.setBackground(new java.awt.Color(240, 240, 240));
        HeightTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        HeightTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightTxtFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Weight:");

        WeightTxtField.setBackground(new java.awt.Color(240, 240, 240));
        WeightTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        WeightTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightTxtFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Social Security number:");

        SSNTxtField.setBackground(new java.awt.Color(240, 240, 240));
        SSNTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        SSNTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSNTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BirthdayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhonenumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSNTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(317, 317, 317))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel9)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FirstnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LastnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PhonenumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BirthdayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AgeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(HeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(WeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSNTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FirstnameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameTxtFieldActionPerformed

    private void LastnameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameTxtFieldActionPerformed

    private void PhonenumTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonenumTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonenumTxtFieldActionPerformed

    private void BirthdayTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthdayTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthdayTxtFieldActionPerformed

    private void AgeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTxtFieldActionPerformed

    private void HeightTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightTxtFieldActionPerformed

    private void WeightTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightTxtFieldActionPerformed

    private void SSNTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSNTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSNTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeTxtField;
    private javax.swing.JTextField BirthdayTxtField;
    private javax.swing.JTextField FirstnameTxtField;
    private javax.swing.JTextField HeightTxtField;
    private javax.swing.JTextField LastnameTxtField;
    private javax.swing.JTextField PhonenumTxtField;
    private javax.swing.JTextField SSNTxtField;
    private javax.swing.JTextField WeightTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
