/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.SavingAccount;
/**
 *
 * @author liuyi
 */
public class ViewSavingAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSavingAccountJPanel
     */

    public ViewSavingAccountJPanel(SavingAccount savingaccount) {
        initComponents();
        displaySavingAccoount(savingaccount);
    }
    private void displaySavingAccoount(SavingAccount savingaccount){
      String number=savingaccount.getAccountnum();
      AccountnumTxtField.setText(number);
      AccountnumTxtField.setEnabled(false);
      String balance=savingaccount.getBalance();
      BalanceTxtField.setText(balance);
      BalanceTxtField.setEnabled(false);
      String name=savingaccount.getBankname();
      BanknameTxtField.setText(name);
      BanknameTxtField.setEnabled(false);
      String routing=savingaccount.getRoutingnum();
      RoutingnumTxtField.setText(routing);
      RoutingnumTxtField.setEnabled(false);
      String type=savingaccount.getType();
      TypeTxtField.setText(type);
      TypeTxtField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        RoutingnumTxtField = new javax.swing.JTextField();
        BalanceTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AccountnumTxtField = new javax.swing.JTextField();
        BanknameTxtField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TypeTxtField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1010, 1166));

        jLabel22.setBackground(java.awt.Color.white);
        jLabel22.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("Account type:");

        RoutingnumTxtField.setBackground(new java.awt.Color(240, 240, 240));
        RoutingnumTxtField.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        RoutingnumTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoutingnumTxtFieldActionPerformed(evt);
            }
        });

        BalanceTxtField.setBackground(new java.awt.Color(240, 240, 240));
        BalanceTxtField.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        BalanceTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceTxtFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setText("Saving Account Information");

        AccountnumTxtField.setBackground(new java.awt.Color(240, 240, 240));
        AccountnumTxtField.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        AccountnumTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountnumTxtFieldActionPerformed(evt);
            }
        });

        BanknameTxtField.setBackground(new java.awt.Color(240, 240, 240));
        BanknameTxtField.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        BanknameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanknameTxtFieldActionPerformed(evt);
            }
        });

        jLabel21.setBackground(java.awt.Color.white);
        jLabel21.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Account balance:");

        TypeTxtField.setBackground(new java.awt.Color(240, 240, 240));
        TypeTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        TypeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeTxtFieldActionPerformed(evt);
            }
        });

        jLabel19.setBackground(java.awt.Color.white);
        jLabel19.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Bank routing number:");

        jLabel20.setBackground(java.awt.Color.white);
        jLabel20.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("Bank account number:");

        jLabel18.setBackground(java.awt.Color.white);
        jLabel18.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Bank name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TypeTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(BalanceTxtField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RoutingnumTxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(BanknameTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccountnumTxtField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabel22))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(319, 319, 319))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel9)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(BanknameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(RoutingnumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(AccountnumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(BalanceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(TypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RoutingnumTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoutingnumTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoutingnumTxtFieldActionPerformed

    private void BalanceTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceTxtFieldActionPerformed

    private void AccountnumTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountnumTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountnumTxtFieldActionPerformed

    private void BanknameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanknameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BanknameTxtFieldActionPerformed

    private void TypeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountnumTxtField;
    private javax.swing.JTextField BalanceTxtField;
    private javax.swing.JTextField BanknameTxtField;
    private javax.swing.JTextField RoutingnumTxtField;
    private javax.swing.JTextField TypeTxtField;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
