/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Medical;

/**
 *
 * @author liuyi
 */
public class ViewMedicalRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMedicalRecordJPanel
     */

    public ViewMedicalRecordJPanel(Medical medical) {
        initComponents();
        displayMedical(medical); 
    }
private void displayMedical(Medical medical){
    String one=medical.getAlergy1();
    Alergy1TxtField.setText(one);
    Alergy1TxtField.setEnabled(false);
    String two=medical.getAlergy2();
    Alergy2TxtField.setText(two);
    Alergy2TxtField.setEnabled(false);
    String three=medical.getAlergy3();
    Alergy3TxtField.setText(three);
    Alergy3TxtField.setEnabled(false);
    String record=medical.getRecordNum();
    RecordTxtField.setText(record);
    RecordTxtField.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        RecordTxtField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Alergy1TxtField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Alergy2TxtField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Alergy3TxtField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1010, 1166));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setText("Medical Record Information");

        RecordTxtField.setBackground(new java.awt.Color(240, 240, 240));
        RecordTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        RecordTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordTxtFieldActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("Medical record number:");

        jLabel29.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText("Allergy 1:");

        Alergy1TxtField.setBackground(new java.awt.Color(240, 240, 240));
        Alergy1TxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        Alergy1TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy1TxtFieldActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setText("Allergy 2:");

        Alergy2TxtField.setBackground(new java.awt.Color(240, 240, 240));
        Alergy2TxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        Alergy2TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy2TxtFieldActionPerformed(evt);
            }
        });

        jLabel31.setBackground(java.awt.Color.white);
        jLabel31.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 102));
        jLabel31.setText("Alergy 3:");

        Alergy3TxtField.setBackground(new java.awt.Color(240, 240, 240));
        Alergy3TxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        Alergy3TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy3TxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alergy3TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Alergy2TxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                .addComponent(Alergy1TxtField)
                                .addComponent(RecordTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel9)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel9)
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(RecordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(Alergy1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(Alergy2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alergy3TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(405, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RecordTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecordTxtFieldActionPerformed

    private void Alergy1TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy1TxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy1TxtFieldActionPerformed

    private void Alergy2TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy2TxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy2TxtFieldActionPerformed

    private void Alergy3TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy3TxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy3TxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alergy1TxtField;
    private javax.swing.JTextField Alergy2TxtField;
    private javax.swing.JTextField Alergy3TxtField;
    private javax.swing.JTextField RecordTxtField;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
