/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.License;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author liuyi
 */
public class ViewDriverLicenseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDriverLicenseJPanel
     */

    public ViewDriverLicenseJPanel(License license) {
        initComponents();
        displayLicense(license);
        display2();
    }
private void displayLicense(License license){
    String blood=license.getBloodtype();
    BloodtypeTxtField.setText(blood);
    BloodtypeTxtField.setEnabled(false);
    String expiration=license.getExpiration();
    ExpirationTxtField.setText(expiration);
    ExpirationTxtField.setEnabled(false);
    String issued=license.getIssueddate();
    IssuedTxtField.setText(issued);
    IssuedTxtField.setEnabled(false);
    String number=license.getLicensenum();
    LicensenumTxtField.setText(number);
    LicensenumTxtField.setEnabled(false);
    }
private void display2(){
 
        ImageIcon icon;
        icon = new ImageIcon(CreateDriverLicenseJPanel.path);
        icon.setImage(icon.getImage().getScaledInstance(450, 450, Image.SCALE_DEFAULT));
        picture.setIcon(icon);
        picture.setEnabled(false);
}
    /**
     * This method is cal
     * led from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IssuedTxtField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        LicensenumTxtField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ExpirationTxtField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        BloodtypeTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1010, 1166));

        IssuedTxtField.setBackground(new java.awt.Color(240, 240, 240));
        IssuedTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        IssuedTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuedTxtFieldActionPerformed(evt);
            }
        });

        jLabel23.setBackground(java.awt.Color.white);
        jLabel23.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setText("License number:");

        LicensenumTxtField.setBackground(new java.awt.Color(240, 240, 240));
        LicensenumTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        LicensenumTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicensenumTxtFieldActionPerformed(evt);
            }
        });

        jLabel24.setBackground(java.awt.Color.white);
        jLabel24.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("Date it was issued:");

        jLabel25.setBackground(java.awt.Color.white);
        jLabel25.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 102));
        jLabel25.setText("Date of expiration:");

        ExpirationTxtField.setBackground(new java.awt.Color(240, 240, 240));
        ExpirationTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        ExpirationTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpirationTxtFieldActionPerformed(evt);
            }
        });

        jLabel26.setBackground(java.awt.Color.white);
        jLabel26.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("blood type:");

        BloodtypeTxtField.setBackground(new java.awt.Color(240, 240, 240));
        BloodtypeTxtField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        BloodtypeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodtypeTxtFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setText("Driver License Information");

        picture.setBackground(java.awt.Color.white);
        picture.setForeground(new java.awt.Color(255, 255, 255));
        picture.setText("picture");
        picture.setToolTipText("Picture");

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("Picture is below:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BloodtypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IssuedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ExpirationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LicensenumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel27)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel9)))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel9)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LicensenumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(IssuedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ExpirationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(BloodtypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(180, 180, 180))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IssuedTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuedTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IssuedTxtFieldActionPerformed

    private void LicensenumTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicensenumTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicensenumTxtFieldActionPerformed

    private void ExpirationTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpirationTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpirationTxtFieldActionPerformed

    private void BloodtypeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodtypeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodtypeTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BloodtypeTxtField;
    private javax.swing.JTextField ExpirationTxtField;
    private javax.swing.JTextField IssuedTxtField;
    private javax.swing.JTextField LicensenumTxtField;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel picture;
    // End of variables declaration//GEN-END:variables
}
