/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Address;
import Business.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author Richard
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;
    private Address address;
     public MainJFrame() {
        initComponents();
        
        
    }
    
    public MainJFrame(Person person) {
        initComponents();
        this.person = person;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddressJPanel = new javax.swing.JPanel();
        WorkAdJPanel = new javax.swing.JPanel();
        WStreetL1JLab = new javax.swing.JLabel();
        WstreetL2JLab = new javax.swing.JLabel();
        WcityJLab = new javax.swing.JLabel();
        WstateJLab = new javax.swing.JLabel();
        WzipcodeJLab = new javax.swing.JLabel();
        WcountJLab = new javax.swing.JLabel();
        WstL1JTF = new javax.swing.JTextField();
        WstL2JTF = new javax.swing.JTextField();
        WcityJTF = new javax.swing.JTextField();
        WstateJTF = new javax.swing.JTextField();
        WzipcodeJTF = new javax.swing.JTextField();
        WcountryJTF = new javax.swing.JTextField();
        LocalAdJPanel = new javax.swing.JPanel();
        LStreetL1JLab1 = new javax.swing.JLabel();
        LstL1JTF1 = new javax.swing.JTextField();
        LstreetL2JLab1 = new javax.swing.JLabel();
        LstL2JTF1 = new javax.swing.JTextField();
        LcityJLab1 = new javax.swing.JLabel();
        LcityJTF1 = new javax.swing.JTextField();
        LstateJLab1 = new javax.swing.JLabel();
        LstateJTF1 = new javax.swing.JTextField();
        LzipcodeJLab1 = new javax.swing.JLabel();
        LzipcodeJTF1 = new javax.swing.JTextField();
        LcountJLab1 = new javax.swing.JLabel();
        LcountryJTF1 = new javax.swing.JTextField();
        HomeAdJPanel = new javax.swing.JPanel();
        HstreetL1JLab2 = new javax.swing.JLabel();
        HstL1JTF2 = new javax.swing.JTextField();
        HstreetL2JLab2 = new javax.swing.JLabel();
        HstL2JTF2 = new javax.swing.JTextField();
        HcityJLab2 = new javax.swing.JLabel();
        HcityJTF2 = new javax.swing.JTextField();
        HstateJLab2 = new javax.swing.JLabel();
        HstateJTF2 = new javax.swing.JTextField();
        HzipcodeJLab2 = new javax.swing.JLabel();
        HzipcodeJTF2 = new javax.swing.JTextField();
        HcountJLab2 = new javax.swing.JLabel();
        HcountryJTF2 = new javax.swing.JTextField();
        PersonJPanel = new javax.swing.JPanel();
        firstNLa = new javax.swing.JLabel();
        lastNLa = new javax.swing.JLabel();
        DateLa = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        LstNTF = new javax.swing.JTextField();
        FirNTF = new javax.swing.JTextField();
        SubmitJB = new javax.swing.JButton();
        ReturnJB = new javax.swing.JButton();
        personProfileJLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Person Profile");

        AddressJPanel.setPreferredSize(new java.awt.Dimension(900, 270));
        AddressJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WorkAdJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Work Address"));

        WStreetL1JLab.setText("Street Line1");

        WstreetL2JLab.setText("Street Line2");

        WcityJLab.setText("City");

        WstateJLab.setText("State");

        WzipcodeJLab.setText("Zip Code");

        WcountJLab.setText("Country");

        javax.swing.GroupLayout WorkAdJPanelLayout = new javax.swing.GroupLayout(WorkAdJPanel);
        WorkAdJPanel.setLayout(WorkAdJPanelLayout);
        WorkAdJPanelLayout.setHorizontalGroup(
            WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAdJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WStreetL1JLab)
                    .addComponent(WcountJLab)
                    .addComponent(WzipcodeJLab)
                    .addComponent(WstateJLab)
                    .addComponent(WcityJLab)
                    .addComponent(WstreetL2JLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WstL1JTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WstL2JTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WcityJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WstateJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WzipcodeJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WcountryJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        WorkAdJPanelLayout.setVerticalGroup(
            WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAdJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(WorkAdJPanelLayout.createSequentialGroup()
                        .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WStreetL1JLab)
                            .addComponent(WstL1JTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WstreetL2JLab))
                    .addComponent(WstL2JTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WcityJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WcityJLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WstateJLab)
                    .addComponent(WstateJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WzipcodeJLab)
                    .addComponent(WzipcodeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WcountJLab)
                    .addComponent(WcountryJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        AddressJPanel.add(WorkAdJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 250));

        LocalAdJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Local Address"));

        LStreetL1JLab1.setText("Street Line1");

        LstreetL2JLab1.setText("Street Line2");

        LcityJLab1.setText("City");

        LstateJLab1.setText("State");

        LzipcodeJLab1.setText("Zip Code");

        LcountJLab1.setText("Country");

        javax.swing.GroupLayout LocalAdJPanelLayout = new javax.swing.GroupLayout(LocalAdJPanel);
        LocalAdJPanel.setLayout(LocalAdJPanelLayout);
        LocalAdJPanelLayout.setHorizontalGroup(
            LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocalAdJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LStreetL1JLab1)
                    .addComponent(LcountJLab1)
                    .addComponent(LzipcodeJLab1)
                    .addComponent(LstateJLab1)
                    .addComponent(LcityJLab1)
                    .addComponent(LstreetL2JLab1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LstL1JTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LstL2JTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LcityJTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LstateJTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LzipcodeJTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LcountryJTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        LocalAdJPanelLayout.setVerticalGroup(
            LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocalAdJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LocalAdJPanelLayout.createSequentialGroup()
                        .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LStreetL1JLab1)
                            .addComponent(LstL1JTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LstreetL2JLab1))
                    .addComponent(LstL2JTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LcityJTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LcityJLab1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LstateJLab1)
                    .addComponent(LstateJTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LzipcodeJLab1)
                    .addComponent(LzipcodeJTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LcountJLab1)
                    .addComponent(LcountryJTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        AddressJPanel.add(LocalAdJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 210, 250));

        HomeAdJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sweet Home Address"));

        HstreetL1JLab2.setText("Street Line1");

        HstreetL2JLab2.setText("Street Line2");

        HcityJLab2.setText("City");

        HstateJLab2.setText("State");

        HzipcodeJLab2.setText("Zip Code");

        HcountJLab2.setText("Country");

        javax.swing.GroupLayout HomeAdJPanelLayout = new javax.swing.GroupLayout(HomeAdJPanel);
        HomeAdJPanel.setLayout(HomeAdJPanelLayout);
        HomeAdJPanelLayout.setHorizontalGroup(
            HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeAdJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HstreetL1JLab2)
                    .addComponent(HcountJLab2)
                    .addComponent(HzipcodeJLab2)
                    .addComponent(HstateJLab2)
                    .addComponent(HcityJLab2)
                    .addComponent(HstreetL2JLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HstL1JTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HstL2JTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HcityJTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HstateJTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HzipcodeJTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HcountryJTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        HomeAdJPanelLayout.setVerticalGroup(
            HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeAdJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HomeAdJPanelLayout.createSequentialGroup()
                        .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HstreetL1JLab2)
                            .addComponent(HstL1JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HstreetL2JLab2))
                    .addComponent(HstL2JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HcityJTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HcityJLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HstateJLab2)
                    .addComponent(HstateJTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HzipcodeJLab2)
                    .addComponent(HzipcodeJTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HcountJLab2)
                    .addComponent(HcountryJTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        AddressJPanel.add(HomeAdJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 230, 250));

        getContentPane().add(AddressJPanel, java.awt.BorderLayout.PAGE_END);

        PersonJPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        PersonJPanel.setPreferredSize(new java.awt.Dimension(900, 210));

        firstNLa.setText("First Name:");

        lastNLa.setText("Last Name:");

        DateLa.setText("DOB(YYYY/MM/DD)");

        FirNTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirNTFActionPerformed(evt);
            }
        });

        SubmitJB.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SubmitJB.setForeground(new java.awt.Color(255, 0, 51));
        SubmitJB.setText("SUBMIT");
        SubmitJB.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        SubmitJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitJBActionPerformed(evt);
            }
        });

        ReturnJB.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ReturnJB.setForeground(new java.awt.Color(0, 204, 255));
        ReturnJB.setText("RETURN");
        ReturnJB.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        ReturnJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnJBActionPerformed(evt);
            }
        });

        personProfileJLab.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        personProfileJLab.setForeground(new java.awt.Color(255, 51, 0));
        personProfileJLab.setText("Person Profile");
        personProfileJLab.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        javax.swing.GroupLayout PersonJPanelLayout = new javax.swing.GroupLayout(PersonJPanel);
        PersonJPanel.setLayout(PersonJPanelLayout);
        PersonJPanelLayout.setHorizontalGroup(
            PersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonJPanelLayout.createSequentialGroup()
                .addGroup(PersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonJPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(PersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PersonJPanelLayout.createSequentialGroup()
                                .addComponent(ReturnJB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194)
                                .addComponent(SubmitJB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PersonJPanelLayout.createSequentialGroup()
                                .addGroup(PersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstNLa)
                                    .addComponent(lastNLa))
                                .addGap(40, 40, 40)
                                .addGroup(PersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FirNTF, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LstNTF, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(DateLa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PersonJPanelLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(personProfileJLab, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        PersonJPanelLayout.setVerticalGroup(
            PersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonJPanelLayout.createSequentialGroup()
                .addGroup(PersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonJPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(firstNLa)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personProfileJLab)
                        .addGap(18, 18, 18)
                        .addGroup(PersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateLa)
                            .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(PersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonJPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lastNLa))
                    .addComponent(LstNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReturnJB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitJB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(PersonJPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirNTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirNTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirNTFActionPerformed

    private void SubmitJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitJBActionPerformed
        // TODO add your handling code here:
        
        person.setFirstName(FirNTF.getText());
        person.setLastName(LstNTF.getText());
        person.setBirthDay(dateTF.getText());
        
        address = new Address();
        address.setAddressLine1(WstL1JTF.getText());
        address.setAddressLine2(WstL2JTF.getText());
        address.setCity(WcityJTF.getText());
        address.setCountry(WcountryJTF.getText());
        address.setState(WstateJTF.getText());
        address.setZipCode(WzipcodeJTF.getText());
        person.setWorkAddress(address);
        
        
        address = new Address();
        address.setAddressLine1(LstL1JTF1.getText());
        address.setAddressLine2(LstL2JTF1.getText());
        address.setCity(LcityJTF1.getText());
        address.setCountry(LcountryJTF1.getText());
        address.setState(LstateJTF1.getText());
        address.setZipCode(LzipcodeJTF1.getText());
        person.setLocalAddress(address);
        
        
        address = new Address();
        address.setAddressLine1(HstL1JTF2.getText());
        address.setAddressLine2(HstL2JTF2.getText());
        address.setCity(HcityJTF2.getText());
        address.setCountry(HcountryJTF2.getText());
        address.setState(HstateJTF2.getText());
        address.setZipCode(HzipcodeJTF2.getText());
        person.setHomeAddress(address);
        
        if(person.getFirstName() == null){
            JOptionPane.showMessageDialog(null, "Firstname Can Not Be EMPTY!!!");
            return; 
        }
        if(person.getLastName() == null){
            JOptionPane.showMessageDialog(null, "Lastname Can Not Be EMPTY!!!");
            return; 
        }
        if(person.getBirthDay() == null){
            JOptionPane.showMessageDialog(null, "BirthDay Can Not Be EMPTY!!!");
            return; 
        }
        if(person.getWorkAddress().getAddressLine1() == null){
            JOptionPane.showMessageDialog(null, "Work Address Line1 Can Not Be EMPTY!!!");
            return; 
        }
        if(person.getHomeAddress().getAddressLine1() == null){
            JOptionPane.showMessageDialog(null, "Home Address Line1 Can Not Be EMPTY!!!");
            return; 
        }
        if(person.getLocalAddress() == null){
            JOptionPane.showMessageDialog(null, "Local Address Line1 Can Not Be EMPTY!!!");
            return; 
        }
        
        
        JOptionPane.showMessageDialog(null, "Create successfully","warning", JOptionPane.WARNING_MESSAGE);
        this.dispose();
        WelcomeJFrame welcomeJFrame = new WelcomeJFrame(person);
        welcomeJFrame.setVisible(true);
    }//GEN-LAST:event_SubmitJBActionPerformed

    private void ReturnJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnJBActionPerformed
        // TODO add your handling code here:
        this.dispose();
        WelcomeJFrame welcomeJFrame = new WelcomeJFrame();
        welcomeJFrame.setVisible(true);
    }//GEN-LAST:event_ReturnJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddressJPanel;
    private javax.swing.JLabel DateLa;
    private javax.swing.JTextField FirNTF;
    private javax.swing.JLabel HcityJLab2;
    private javax.swing.JTextField HcityJTF2;
    private javax.swing.JLabel HcountJLab2;
    private javax.swing.JTextField HcountryJTF2;
    private javax.swing.JPanel HomeAdJPanel;
    private javax.swing.JTextField HstL1JTF2;
    private javax.swing.JTextField HstL2JTF2;
    private javax.swing.JLabel HstateJLab2;
    private javax.swing.JTextField HstateJTF2;
    private javax.swing.JLabel HstreetL1JLab2;
    private javax.swing.JLabel HstreetL2JLab2;
    private javax.swing.JLabel HzipcodeJLab2;
    private javax.swing.JTextField HzipcodeJTF2;
    private javax.swing.JLabel LStreetL1JLab1;
    private javax.swing.JLabel LcityJLab1;
    private javax.swing.JTextField LcityJTF1;
    private javax.swing.JLabel LcountJLab1;
    private javax.swing.JTextField LcountryJTF1;
    private javax.swing.JPanel LocalAdJPanel;
    private javax.swing.JTextField LstL1JTF1;
    private javax.swing.JTextField LstL2JTF1;
    private javax.swing.JTextField LstNTF;
    private javax.swing.JLabel LstateJLab1;
    private javax.swing.JTextField LstateJTF1;
    private javax.swing.JLabel LstreetL2JLab1;
    private javax.swing.JLabel LzipcodeJLab1;
    private javax.swing.JTextField LzipcodeJTF1;
    private javax.swing.JPanel PersonJPanel;
    private javax.swing.JButton ReturnJB;
    private javax.swing.JButton SubmitJB;
    private javax.swing.JLabel WStreetL1JLab;
    private javax.swing.JLabel WcityJLab;
    private javax.swing.JTextField WcityJTF;
    private javax.swing.JLabel WcountJLab;
    private javax.swing.JTextField WcountryJTF;
    private javax.swing.JPanel WorkAdJPanel;
    private javax.swing.JTextField WstL1JTF;
    private javax.swing.JTextField WstL2JTF;
    private javax.swing.JLabel WstateJLab;
    private javax.swing.JTextField WstateJTF;
    private javax.swing.JLabel WstreetL2JLab;
    private javax.swing.JLabel WzipcodeJLab;
    private javax.swing.JTextField WzipcodeJTF;
    private javax.swing.JTextField dateTF;
    private javax.swing.JLabel firstNLa;
    private javax.swing.JLabel lastNLa;
    private javax.swing.JLabel personProfileJLab;
    // End of variables declaration//GEN-END:variables
}
