/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Address;
import Business.Person;
import javax.swing.JOptionPane;
/**
 *
 * @author Richard
 */
public class ResultJFrame extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form ResultJFrame
     */
    public ResultJFrame() {
        initComponents();
        
    }
    public void initePerson(){
        Person  person = new Person();
        Address address;
        person.setFirstName("Joe");
        person.setLastName("Smith");
        address = new Address();
        address.setAddressLine1("360 Huntington Ave");
        person.setWorkAddress(address); //save address object as a work address

        address = new Address(); // create new address object using the same ref variable
        address.setAddressLine1("100 Main Street"); //insert address info
        person.setLocalAddress(address);

        address = new Address();
        address.setAddressLine1("201 Best Street");
        person.setHomeAddress(address);
        
        firstNameJTX.setText(person.getFirstName());
        lastNameJTX.setText(person.getLastName());
        WstL1JTF.setText(person.getWorkAddress().getAddressLine1());
        HstL1JTF2.setText(person.getHomeAddress().getAddressLine1());
        LstL1JTF1.setText(person.getLocalAddress().getAddressLine1());
        



        
    }
    
    
    public ResultJFrame(Person person) {
        initComponents();
        
        displayPerson(person);
    }
    
    private void displayPerson(Person person){
        String firstName = person.getFirstName();
        firstNameJTX.setText(firstName);
        
        String lastName = person.getLastName();
        lastNameJTX.setText(lastName);
        
        String birthday = person.getBirthDay();
        birthdayJTX.setText(birthday);
        
        Address workAddress = person.getWorkAddress();
        String wStreetLine1 = workAddress.getAddressLine1();
        WstL1JTF.setText(wStreetLine1);
        String wStreetLine2 = workAddress.getAddressLine2();
        WstL2JTF.setText(wStreetLine2);
        String wcity = workAddress.getCity();
        WcityJTF.setText(wcity);
        String wState= workAddress.getState();
        WstateJTF.setText(wState);
        String wCountry = workAddress.getCountry();
        WcountryJTF.setText(wCountry);
        String wZipCode = workAddress.getZipCode();
        WzipcodeJTF.setText(wZipCode);
        
        Address localAddress = person.getLocalAddress();
        String lStreetLine1 = localAddress.getAddressLine1();
        LstL1JTF1.setText(lStreetLine1);
        String lStreetLine2 = localAddress.getAddressLine2();
        LstL2JTF1.setText(lStreetLine2);
        String lcity = localAddress.getCity();
        LcityJTF1.setText(lcity);
        String lState= localAddress.getState();
        LstateJTF1.setText(lState);
        String lCountry = localAddress.getCountry();
        LcountryJTF1.setText(lCountry);
        String lZipCode = localAddress.getZipCode();
        LzipcodeJTF1.setText(lZipCode);
        
        Address homeAddress = person.getHomeAddress();
        String hStreetLine1 = homeAddress.getAddressLine1();
        HstL1JTF2.setText(hStreetLine1);
        String hStreetLine2 = homeAddress.getAddressLine2();
        HstL2JTF2.setText(hStreetLine2);
        String hcity = homeAddress.getCity();
        HcityJTF2.setText(hcity);
        String hState= homeAddress.getState();
        HstateJTF2.setText(hState);
        String hCountry = homeAddress.getCountry();
        HcountryJTF2.setText(hCountry);
        String hZipCode = homeAddress.getZipCode();
        HzipcodeJTF2.setText(hZipCode);
        
        
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personJPanel = new javax.swing.JPanel();
        personInfoJLab = new javax.swing.JLabel();
        firstNameJLa = new javax.swing.JLabel();
        lastNameJLa = new javax.swing.JLabel();
        birthJLa = new javax.swing.JLabel();
        lastNameJTX = new javax.swing.JTextField();
        birthdayJTX = new javax.swing.JTextField();
        firstNameJTX = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        addressJPanel = new javax.swing.JPanel();
        WorkAdJPanel = new javax.swing.JPanel();
        WStreetL1JLab = new javax.swing.JLabel();
        WstreetL2JLab = new javax.swing.JLabel();
        WcityJLab = new javax.swing.JLabel();
        WstateJLab = new javax.swing.JLabel();
        WzipcodeJLab = new javax.swing.JLabel();
        WcountJLab = new javax.swing.JLabel();
        WstL1JTF = new javax.swing.JTextField();
        WstL2JTF = new javax.swing.JTextField();
        WcityJTF = new javax.swing.JTextField();
        WstateJTF = new javax.swing.JTextField();
        WzipcodeJTF = new javax.swing.JTextField();
        WcountryJTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        LocalAdJPanel = new javax.swing.JPanel();
        LStreetL1JLab1 = new javax.swing.JLabel();
        LstL1JTF1 = new javax.swing.JTextField();
        LstreetL2JLab1 = new javax.swing.JLabel();
        LstL2JTF1 = new javax.swing.JTextField();
        LcityJLab1 = new javax.swing.JLabel();
        LcityJTF1 = new javax.swing.JTextField();
        LstateJLab1 = new javax.swing.JLabel();
        LstateJTF1 = new javax.swing.JTextField();
        LzipcodeJLab1 = new javax.swing.JLabel();
        LzipcodeJTF1 = new javax.swing.JTextField();
        LcountJLab1 = new javax.swing.JLabel();
        LcountryJTF1 = new javax.swing.JTextField();
        HomeAdJPanel = new javax.swing.JPanel();
        HstreetL1JLab2 = new javax.swing.JLabel();
        HstL1JTF2 = new javax.swing.JTextField();
        HstreetL2JLab2 = new javax.swing.JLabel();
        HstL2JTF2 = new javax.swing.JTextField();
        HcityJLab2 = new javax.swing.JLabel();
        HcityJTF2 = new javax.swing.JTextField();
        HstateJLab2 = new javax.swing.JLabel();
        HstateJTF2 = new javax.swing.JTextField();
        HzipcodeJLab2 = new javax.swing.JLabel();
        HzipcodeJTF2 = new javax.swing.JTextField();
        HcountJLab2 = new javax.swing.JLabel();
        HcountryJTF2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        personJPanel.setPreferredSize(new java.awt.Dimension(250, 300));

        personInfoJLab.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        personInfoJLab.setForeground(new java.awt.Color(255, 51, 51));
        personInfoJLab.setText("PEROSN INFORMATION");
        personInfoJLab.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        firstNameJLa.setText("1. First Name:");

        lastNameJLa.setText("2. Last Name:");

        birthJLa.setText("3. Birthday");

        lastNameJTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameJTXActionPerformed(evt);
            }
        });

        birthdayJTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayJTXActionPerformed(evt);
            }
        });

        firstNameJTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameJTXActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("RETURN");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personJPanelLayout = new javax.swing.GroupLayout(personJPanel);
        personJPanel.setLayout(personJPanelLayout);
        personJPanelLayout.setHorizontalGroup(
            personJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personJPanelLayout.createSequentialGroup()
                .addGroup(personJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personJPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(personJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personJPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(personJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameJLa)
                                    .addComponent(firstNameJLa)
                                    .addComponent(birthJLa)))
                            .addGroup(personJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(firstNameJTX)
                                .addComponent(lastNameJTX, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(birthdayJTX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(personJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personInfoJLab))
                    .addGroup(personJPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        personJPanelLayout.setVerticalGroup(
            personJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personInfoJLab)
                .addGap(50, 50, 50)
                .addComponent(firstNameJLa)
                .addGap(18, 18, 18)
                .addComponent(firstNameJTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lastNameJLa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastNameJTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(birthJLa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(birthdayJTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(personJPanel, java.awt.BorderLayout.CENTER);

        addressJPanel.setPreferredSize(new java.awt.Dimension(730, 300));

        WorkAdJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Work Address"));

        WStreetL1JLab.setText("Street Line1");

        WstreetL2JLab.setText("Street Line2");

        WcityJLab.setText("City");

        WstateJLab.setText("State");

        WzipcodeJLab.setText("Zip Code");

        WcountJLab.setText("Country");

        javax.swing.GroupLayout WorkAdJPanelLayout = new javax.swing.GroupLayout(WorkAdJPanel);
        WorkAdJPanel.setLayout(WorkAdJPanelLayout);
        WorkAdJPanelLayout.setHorizontalGroup(
            WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAdJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WStreetL1JLab)
                    .addComponent(WcountJLab)
                    .addComponent(WzipcodeJLab)
                    .addComponent(WstateJLab)
                    .addComponent(WcityJLab)
                    .addComponent(WstreetL2JLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WstL1JTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WstL2JTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WcityJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WstateJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WzipcodeJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WcountryJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        WorkAdJPanelLayout.setVerticalGroup(
            WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAdJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(WorkAdJPanelLayout.createSequentialGroup()
                        .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WStreetL1JLab)
                            .addComponent(WstL1JTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WstreetL2JLab))
                    .addComponent(WstL2JTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WcityJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WcityJLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WstateJLab)
                    .addComponent(WstateJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WzipcodeJLab)
                    .addComponent(WzipcodeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WorkAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WcountJLab)
                    .addComponent(WcountryJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("ADDRESS INFORMATION");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        LocalAdJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Local Address"));

        LStreetL1JLab1.setText("Street Line1");

        LstreetL2JLab1.setText("Street Line2");

        LcityJLab1.setText("City");

        LstateJLab1.setText("State");

        LzipcodeJLab1.setText("Zip Code");

        LcountJLab1.setText("Country");

        javax.swing.GroupLayout LocalAdJPanelLayout = new javax.swing.GroupLayout(LocalAdJPanel);
        LocalAdJPanel.setLayout(LocalAdJPanelLayout);
        LocalAdJPanelLayout.setHorizontalGroup(
            LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocalAdJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LStreetL1JLab1)
                    .addComponent(LcountJLab1)
                    .addComponent(LzipcodeJLab1)
                    .addComponent(LstateJLab1)
                    .addComponent(LcityJLab1)
                    .addComponent(LstreetL2JLab1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LstL1JTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LstL2JTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LcityJTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LstateJTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LzipcodeJTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LcountryJTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        LocalAdJPanelLayout.setVerticalGroup(
            LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocalAdJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LocalAdJPanelLayout.createSequentialGroup()
                        .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LStreetL1JLab1)
                            .addComponent(LstL1JTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LstreetL2JLab1))
                    .addComponent(LstL2JTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LcityJTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LcityJLab1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LstateJLab1)
                    .addComponent(LstateJTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LzipcodeJLab1)
                    .addComponent(LzipcodeJTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LocalAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LcountJLab1)
                    .addComponent(LcountryJTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        HomeAdJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sweet Home Address"));

        HstreetL1JLab2.setText("Street Line1");

        HstreetL2JLab2.setText("Street Line2");

        HcityJLab2.setText("City");

        HstateJLab2.setText("State");

        HzipcodeJLab2.setText("Zip Code");

        HcountJLab2.setText("Country");

        javax.swing.GroupLayout HomeAdJPanelLayout = new javax.swing.GroupLayout(HomeAdJPanel);
        HomeAdJPanel.setLayout(HomeAdJPanelLayout);
        HomeAdJPanelLayout.setHorizontalGroup(
            HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeAdJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HstreetL1JLab2)
                    .addComponent(HcountJLab2)
                    .addComponent(HzipcodeJLab2)
                    .addComponent(HstateJLab2)
                    .addComponent(HcityJLab2)
                    .addComponent(HstreetL2JLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HstL1JTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HstL2JTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HcityJTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HstateJTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HzipcodeJTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HcountryJTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        HomeAdJPanelLayout.setVerticalGroup(
            HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeAdJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HomeAdJPanelLayout.createSequentialGroup()
                        .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HstreetL1JLab2)
                            .addComponent(HstL1JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HstreetL2JLab2))
                    .addComponent(HstL2JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HcityJTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HcityJLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HstateJLab2)
                    .addComponent(HstateJTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HzipcodeJLab2)
                    .addComponent(HzipcodeJTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeAdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HcountJLab2)
                    .addComponent(HcountryJTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addressJPanelLayout = new javax.swing.GroupLayout(addressJPanel);
        addressJPanel.setLayout(addressJPanelLayout);
        addressJPanelLayout.setHorizontalGroup(
            addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressJPanelLayout.createSequentialGroup()
                .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addressJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WorkAdJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HomeAdJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LocalAdJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addressJPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel5)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        addressJPanelLayout.setVerticalGroup(
            addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressJPanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomeAdJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkAdJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocalAdJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(addressJPanel, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameJTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameJTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameJTXActionPerformed

    private void birthdayJTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayJTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayJTXActionPerformed

    private void firstNameJTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameJTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameJTXActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        WelcomeJFrame welcomeJFrame = new WelcomeJFrame();
        welcomeJFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HcityJLab2;
    private javax.swing.JTextField HcityJTF2;
    private javax.swing.JLabel HcountJLab2;
    private javax.swing.JTextField HcountryJTF2;
    private javax.swing.JPanel HomeAdJPanel;
    private javax.swing.JTextField HstL1JTF2;
    private javax.swing.JTextField HstL2JTF2;
    private javax.swing.JLabel HstateJLab2;
    private javax.swing.JTextField HstateJTF2;
    private javax.swing.JLabel HstreetL1JLab2;
    private javax.swing.JLabel HstreetL2JLab2;
    private javax.swing.JLabel HzipcodeJLab2;
    private javax.swing.JTextField HzipcodeJTF2;
    private javax.swing.JLabel LStreetL1JLab1;
    private javax.swing.JLabel LcityJLab1;
    private javax.swing.JTextField LcityJTF1;
    private javax.swing.JLabel LcountJLab1;
    private javax.swing.JTextField LcountryJTF1;
    private javax.swing.JPanel LocalAdJPanel;
    private javax.swing.JTextField LstL1JTF1;
    private javax.swing.JTextField LstL2JTF1;
    private javax.swing.JLabel LstateJLab1;
    private javax.swing.JTextField LstateJTF1;
    private javax.swing.JLabel LstreetL2JLab1;
    private javax.swing.JLabel LzipcodeJLab1;
    private javax.swing.JTextField LzipcodeJTF1;
    private javax.swing.JLabel WStreetL1JLab;
    private javax.swing.JLabel WcityJLab;
    private javax.swing.JTextField WcityJTF;
    private javax.swing.JLabel WcountJLab;
    private javax.swing.JTextField WcountryJTF;
    private javax.swing.JPanel WorkAdJPanel;
    private javax.swing.JTextField WstL1JTF;
    private javax.swing.JTextField WstL2JTF;
    private javax.swing.JLabel WstateJLab;
    private javax.swing.JTextField WstateJTF;
    private javax.swing.JLabel WstreetL2JLab;
    private javax.swing.JLabel WzipcodeJLab;
    private javax.swing.JTextField WzipcodeJTF;
    private javax.swing.JPanel addressJPanel;
    private javax.swing.JLabel birthJLa;
    private javax.swing.JTextField birthdayJTX;
    private javax.swing.JLabel firstNameJLa;
    private javax.swing.JTextField firstNameJTX;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lastNameJLa;
    private javax.swing.JTextField lastNameJTX;
    private javax.swing.JLabel personInfoJLab;
    private javax.swing.JPanel personJPanel;
    // End of variables declaration//GEN-END:variables
}
