/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignsHistory;
import javax.swing.table.DefaultTableModel; 
import Business.VitalSigns;
import javax.swing.JOptionPane;
        

/**
 *
 * @author Richard
 */
public class ViewVitalJPanel extends javax.swing.JPanel {
    
    private VitalSignsHistory vsh;
    /**
     * Creates new form ViewVitalSingnsJPanel
     */
    public ViewVitalJPanel() {
        initComponents();
        
    }

    ViewVitalJPanel(VitalSignsHistory vsh) {
         initComponents();
         this.vsh = vsh;
         populateTable();
      
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) jtbVitalSigns.getModel();
        dtm.setRowCount(0);
        
        for(VitalSigns vs : vsh.getVitalSignsHistory()){
            Object[] row = new Object[2];
            row[0] = vs;
            row[1] = vs.getBlood();
            dtm.addRow(row);
            
        }
    }
    
    public void restTextField(){
         jTFBlood.setText("");
            jTFDate.setText("");
            jTFPulse.setText("");
            jTFTemp.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbView = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbVitalSigns = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblTemp = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jTFPulse = new javax.swing.JTextField();
        jTFTemp = new javax.swing.JTextField();
        jTFDate = new javax.swing.JTextField();
        lblBlood = new javax.swing.JLabel();
        jTFBlood = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(600, 500));

        jlbView.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbView.setForeground(new java.awt.Color(255, 51, 51));
        jlbView.setText("View Vital Signs");
        jlbView.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jtbVitalSigns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "BloodPressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbVitalSigns);

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblTemp.setText("Temperature");

        lblPulse.setText("Pulse");

        lblDate.setText("Date");

        jTFPulse.setEnabled(false);

        jTFTemp.setEnabled(false);

        jTFDate.setEnabled(false);

        lblBlood.setText("Blood Pressure");

        jTFBlood.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addGap(77, 77, 77)
                        .addComponent(jTFDate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPulse)
                        .addGap(77, 77, 77)
                        .addComponent(jTFPulse, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTemp)
                        .addGap(77, 77, 77)
                        .addComponent(jTFTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBlood)
                        .addGap(77, 77, 77)
                        .addComponent(jTFBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(154, 154, 154)
                            .addComponent(jlbView))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlbView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemp)
                    .addComponent(jTFTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlood)
                    .addComponent(jTFBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulse)
                    .addComponent(jTFPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(jTFDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtbVitalSigns.getSelectedRow();
        if(selectedRow >= 0){
            
            VitalSigns vs = (VitalSigns)jtbVitalSigns.getValueAt(selectedRow, 0);
            jTFBlood.setText(String.valueOf(vs.getBlood()));
            jTFDate.setText(vs.getDate());
            jTFPulse.setText(String.valueOf(vs.getPulse()));
            jTFTemp.setText(String.valueOf(vs.getTemperature()));
            
                    
            
        }else{
            JOptionPane.showMessageDialog(null, "Please selected any row!!!","Alert", JOptionPane.ERROR);
        }
            
        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtbVitalSigns.getSelectedRow();
        if(selectedRow >= 0){
            int dialogRes = JOptionPane.showConfirmDialog(null, "This is Vital Sign, Do you want to delete it?");
            if(dialogRes == JOptionPane.YES_OPTION){
               VitalSigns vs = (VitalSigns)jtbVitalSigns.getValueAt(selectedRow, 0);
               vsh.deleteVitals(vs);
               JOptionPane.showMessageDialog(null, "You have delete this  Vital Sign!!");
               populateTable();
               restTextField();
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Please selected any row!!!","Alert", JOptionPane.ERROR);
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFBlood;
    private javax.swing.JTextField jTFDate;
    private javax.swing.JTextField jTFPulse;
    private javax.swing.JTextField jTFTemp;
    private javax.swing.JLabel jlbView;
    private javax.swing.JTable jtbVitalSigns;
    private javax.swing.JLabel lblBlood;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemp;
    // End of variables declaration//GEN-END:variables
}
