/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import Business.Account;
import javax.swing.JOptionPane;

/**
 *
 * @author Richard
 */
public class AccountInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountInfo
     */
    private Person person;
    private String accountType;
    int type;
    public AccountInfoJPanel(){
        initComponents();
    }
    
    public void inite(String accountType){
        accountBalanceJTF.setText("1000.00");
            
            accountTypeJTF.setText(accountType);
            accountTypeJTF.setEnabled(false);
            
            bankAccNumJTF.setText("1040 1024 1234 098");
            
            bankNameJTF.setText("Jack");
            
            bankRoutNumJTF.setText("984");
            type=2;
        
    }
    
    
    public AccountInfoJPanel(Person person, String accountType, int type) {
        initComponents();
        this.person = person;
        this.accountType = accountType;
        this.type = type;
        accountTypeJTF.setText(accountType);
        accountTypeJTF.setEnabled(false);
        if(type == 2){
            displayPerson(person, accountType);
        }
        
    }
    private void displayPerson(Person person, String accountType){
        
        if(accountType.equals("saving")){
            Account account= person.getSavingAccount();
            String accountBalance = account.getAccountBalance();
            accountBalanceJTF.setText(accountBalance);
            accountBalanceJTF.setEnabled(false);
            
            accountTypeJTF.setText(accountType);
            accountTypeJTF.setEnabled(false);
            
            String accountNum = account.getBankAccountNumber();
            bankAccNumJTF.setText(accountNum);
            bankAccNumJTF.setEnabled(false);
            
            String bankName = account.getBankName();
            bankNameJTF.setText(bankName);
            bankNameJTF.setEnabled(false);
            
            String bankRoutingNum = account.getBankRountingNumber();
            bankRoutNumJTF.setText(bankRoutingNum);
            bankRoutNumJTF.setEnabled(false);
        
        
        }else if(accountType.equals("checking")){
            Account account= person.getCheckingAccount();
            String accountBalance = account.getAccountBalance();
            accountBalanceJTF.setText(accountBalance);
            accountBalanceJTF.setEnabled(false);
            
            accountTypeJTF.setText(accountType);
            accountTypeJTF.setEnabled(false);
            
            String accountNum = account.getBankAccountNumber();
            bankAccNumJTF.setText(accountNum);
            bankAccNumJTF.setEnabled(false);
            
            String bankName = account.getBankName();
            bankNameJTF.setText(bankName);
            bankNameJTF.setEnabled(false);
            
            String bankRoutingNum = account.getBankRountingNumber();
            bankRoutNumJTF.setText(bankRoutingNum);
            bankRoutNumJTF.setEnabled(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "error");
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountInfo = new javax.swing.JPanel();
        bankNameJLa = new javax.swing.JLabel();
        bankNameJTF = new javax.swing.JTextField();
        bankRoutNumJLab = new javax.swing.JLabel();
        bankRoutNumJTF = new javax.swing.JTextField();
        bankAccNumJLab = new javax.swing.JLabel();
        bankAccNumJTF = new javax.swing.JTextField();
        accountBalanceJLab = new javax.swing.JLabel();
        accountBalanceJTF = new javax.swing.JTextField();
        accountTypeJLab = new javax.swing.JLabel();
        accountTypeJTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 500));

        AccountInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Account Information"));

        bankNameJLa.setText("Bank name");

        bankRoutNumJLab.setText("bank routing number");

        bankAccNumJLab.setText("bank account number");

        accountBalanceJLab.setText("account balance");

        accountTypeJLab.setText("account type ");

        accountTypeJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypeJTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccountInfoLayout = new javax.swing.GroupLayout(AccountInfo);
        AccountInfo.setLayout(AccountInfoLayout);
        AccountInfoLayout.setHorizontalGroup(
            AccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountInfoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(AccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankNameJLa)
                    .addComponent(accountTypeJLab)
                    .addComponent(accountBalanceJLab)
                    .addComponent(bankAccNumJLab)
                    .addComponent(bankRoutNumJLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankNameJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankRoutNumJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankAccNumJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountBalanceJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountTypeJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        AccountInfoLayout.setVerticalGroup(
            AccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountInfoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(AccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AccountInfoLayout.createSequentialGroup()
                        .addGroup(AccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bankNameJLa)
                            .addComponent(bankNameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bankRoutNumJLab))
                    .addComponent(bankRoutNumJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankAccNumJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankAccNumJLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountBalanceJLab)
                    .addComponent(accountBalanceJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountTypeJLab)
                    .addComponent(accountTypeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("SUBMIT&NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(AccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountTypeJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypeJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTypeJTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(type == 2){
            JOptionPane.showMessageDialog(null,"You Cannot Change Information");
            
        }else{
        Account account = new Account();
        account.setAccountBalance(accountBalanceJTF.getText());
        account.setBankAccountNumber(bankAccNumJTF.getText());
        account.setBankName(bankNameJTF.getText());
        account.setBankRountingNumber(bankRoutNumJTF.getText());
        account.setAccountType(accountType);
        if(accountType.equals("saving")){
           person.setSavingAccount(account);
        }else if(accountType.equals("checking")){
            person.setCheckingAccount(account);
        }else{
            JOptionPane.showMessageDialog(null, "error");
            return;
        }
        

        JOptionPane.showMessageDialog(null, "Create Address Information successfully","warning", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountInfo;
    private javax.swing.JLabel accountBalanceJLab;
    private javax.swing.JTextField accountBalanceJTF;
    private javax.swing.JLabel accountTypeJLab;
    private javax.swing.JTextField accountTypeJTF;
    private javax.swing.JLabel bankAccNumJLab;
    private javax.swing.JTextField bankAccNumJTF;
    private javax.swing.JLabel bankNameJLa;
    private javax.swing.JTextField bankNameJTF;
    private javax.swing.JLabel bankRoutNumJLab;
    private javax.swing.JTextField bankRoutNumJTF;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
