/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import Business.DriverLicense;
import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;


/**
 *
 * @author Richard
 */
public class DriverLicenseInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DriverLicenseInfo
     */
    private Person person;
    int type;
    String pictureAddress;
    
    public DriverLicenseInfoJPanel(){
        initComponents();
        inite();
    }
    
    public void inite(){
        
        
        licenseNumJTF.setText("9284646163313212");
       
        bloodTypeJTF.setText("B");
        
        dateExpirJTF.setText("2023/04/04");
        
        dateIssuedJTF.setText("2018/04/04");
        ImageIcon img = new ImageIcon(getClass().getResource("/Interface/i.jpg"));
        img.setImage(img.getImage().getScaledInstance(250, 200, Image.SCALE_DEFAULT));
        imgJLabel.setIcon(img);
        
        type = 2;
        
        
       
        
        
    }
    
    public DriverLicenseInfoJPanel(Person person, int type) {
        initComponents();
        this.person = person;
        this.type = type;
        if(type == 2){
            displayPerson(person);
        }
    }
    
    private void displayPerson(Person person){
        DriverLicense driverLicense = person.getDriverLicense();
        String licenseNum = driverLicense.getLicenseNumber();
        licenseNumJTF.setText(licenseNum);
        licenseNumJTF.setEnabled(false);
        
        String bloodType = driverLicense.getBloodType();
        bloodTypeJTF.setText(bloodType);
        bloodTypeJTF.setEnabled(false);
        
        String dateExpir = driverLicense.getExpirationDate();
        dateExpirJTF.setText(dateExpir);
        dateExpirJTF.setEnabled(false);
        
        String dateIssued = driverLicense.getIssuedDate();
        dateIssuedJTF.setText(dateIssued);
        dateIssuedJTF.setEnabled(false);
        
        String picture = driverLicense.getPicture();
        
        ImageIcon img = new ImageIcon(picture);
        img.setImage(img.getImage().getScaledInstance(250, 200, Image.SCALE_DEFAULT));
        imgJLabel.setIcon(img);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgJLabel = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        driverLiscenseInfo = new javax.swing.JPanel();
        licenseNumJLab = new javax.swing.JLabel();
        licenseNumJTF = new javax.swing.JTextField();
        dateIssuedJLab = new javax.swing.JLabel();
        dateIssuedJTF = new javax.swing.JTextField();
        dateExpirJLab = new javax.swing.JLabel();
        dateExpirJTF = new javax.swing.JTextField();
        bloodTypeJLab = new javax.swing.JLabel();
        bloodTypeJTF = new javax.swing.JTextField();
        pictureJLab = new javax.swing.JLabel();
        chooseFileJB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 500));

        imgJLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        imgJLabel.setPreferredSize(new java.awt.Dimension(250, 200));

        submit.setText("SUBMIT&NEXT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        driverLiscenseInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Driver’s license information"));

        licenseNumJLab.setText("License number");

        dateIssuedJLab.setText("date it was issued");

        dateExpirJLab.setText("date of expiration");

        bloodTypeJLab.setText("blood type");

        pictureJLab.setText("picture");

        chooseFileJB.setText("Chose File");
        chooseFileJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout driverLiscenseInfoLayout = new javax.swing.GroupLayout(driverLiscenseInfo);
        driverLiscenseInfo.setLayout(driverLiscenseInfoLayout);
        driverLiscenseInfoLayout.setHorizontalGroup(
            driverLiscenseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLiscenseInfoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(driverLiscenseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(licenseNumJLab)
                    .addComponent(pictureJLab)
                    .addComponent(bloodTypeJLab)
                    .addComponent(dateExpirJLab)
                    .addComponent(dateIssuedJLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(driverLiscenseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLiscenseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(licenseNumJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateIssuedJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateExpirJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bloodTypeJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chooseFileJB))
                .addContainerGap())
        );
        driverLiscenseInfoLayout.setVerticalGroup(
            driverLiscenseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLiscenseInfoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(driverLiscenseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(driverLiscenseInfoLayout.createSequentialGroup()
                        .addGroup(driverLiscenseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenseNumJLab)
                            .addComponent(licenseNumJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateIssuedJLab))
                    .addComponent(dateIssuedJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driverLiscenseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateExpirJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateExpirJLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driverLiscenseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTypeJLab)
                    .addComponent(bloodTypeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driverLiscenseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pictureJLab)
                    .addComponent(chooseFileJB))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("IMAGE");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(driverLiscenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(submit)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driverLiscenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(type == 2){
            JOptionPane.showMessageDialog(null,"You Cannot Change Information");
            
        }else{
        DriverLicense driverLicense = new DriverLicense();
        driverLicense.setLicenseNumber(licenseNumJTF.getText());
        driverLicense.setBloodType(bloodTypeJTF.getText());
        driverLicense.setIssuedDate(dateIssuedJTF.getText());
        driverLicense.setExpirationDate(dateExpirJTF.getText());
        driverLicense.setPicture(pictureAddress);
        
        person.setDriverLicense(driverLicense);

        JOptionPane.showMessageDialog(null, "Create Driver Information successfully","warning", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_submitActionPerformed

    private void chooseFileJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileJBActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();             //设置选择器
        chooser.setMultiSelectionEnabled(true);             //设为多选
        int returnVal = chooser.showOpenDialog(chooseFileJB);        //是否打开文件选择框
        //System.out.println("returnVal="+returnVal);
 
        if (returnVal == JFileChooser.APPROVE_OPTION) {          //如果符合文件类型
            String filepath = chooser.getSelectedFile().getAbsolutePath();      //获取绝对路径
            pictureAddress = filepath;
            ImageIcon img = new ImageIcon(pictureAddress);
            img.setImage(img.getImage().getScaledInstance(250, 200, Image.SCALE_DEFAULT));
            imgJLabel.setIcon(img);
            //System.out.println(filepath);
            //System.out.println("You chose to open this file: "+ chooser.getSelectedFile().getName());  //输出相对路径
        }

    }//GEN-LAST:event_chooseFileJBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodTypeJLab;
    private javax.swing.JTextField bloodTypeJTF;
    private javax.swing.JButton chooseFileJB;
    private javax.swing.JLabel dateExpirJLab;
    private javax.swing.JTextField dateExpirJTF;
    private javax.swing.JLabel dateIssuedJLab;
    private javax.swing.JTextField dateIssuedJTF;
    private javax.swing.JPanel driverLiscenseInfo;
    private javax.swing.JLabel imgJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel licenseNumJLab;
    private javax.swing.JTextField licenseNumJTF;
    private javax.swing.JLabel pictureJLab;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
