/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import Business.MedicalRecord;
import javax.swing.JOptionPane;

/**
 *
 * @author Richard
 */
public class MedicalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalJPanel
     */
    private Person person;
    int type;
    public MedicalJPanel(){
        initComponents();
    }
    
    public void inite(){
        
        alergy1JTF.setText("Sherry");
        
        alergy2JTF.setText("Jerry");
       
        alergy3JTF.setText("Floor");
     
        medicalRecNumJTF.setText("857-123-1237");
        type = 2;
        
    }
    
    
    public MedicalJPanel(Person person, int type) {
        initComponents();
        this.person = person;
        this.type = type;
         if(type == 2){
            displayPerson(person);
        }
    }
    
    private void displayPerson(Person person){
        MedicalRecord medicalRecord = person.getMedicalRecord();
        String alergy1 = medicalRecord.getAlergy1();
        alergy1JTF.setText(alergy1);
        alergy1JTF.setEnabled(false);
        
        String alergy2 = medicalRecord.getAlergy2();
        alergy2JTF.setText(alergy2);
        alergy2JTF.setEnabled(false);
        
        String alergy3 = medicalRecord.getAlergy3();
        alergy3JTF.setText(alergy3);
        alergy3JTF.setEnabled(false);
        
        String medicalReNum = medicalRecord.getMedicalRecordNum();
        medicalRecNumJTF.setText(medicalReNum);
        medicalRecNumJTF.setEnabled(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicalrecord = new javax.swing.JPanel();
        mediaclReNumJLab = new javax.swing.JLabel();
        medicalRecNumJTF = new javax.swing.JTextField();
        alergy1JLab = new javax.swing.JLabel();
        alergy1JTF = new javax.swing.JTextField();
        alergy2Lab = new javax.swing.JLabel();
        alergy2JTF = new javax.swing.JTextField();
        alergy3JLab = new javax.swing.JLabel();
        alergy3JTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 500));

        medicalrecord.setBorder(javax.swing.BorderFactory.createTitledBorder("Medical Record"));

        mediaclReNumJLab.setText("Medical record number");

        alergy1JLab.setText("Alergy1");

        alergy2Lab.setText("Alergy2");

        alergy3JLab.setText("Alergy3");

        javax.swing.GroupLayout medicalrecordLayout = new javax.swing.GroupLayout(medicalrecord);
        medicalrecord.setLayout(medicalrecordLayout);
        medicalrecordLayout.setHorizontalGroup(
            medicalrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicalrecordLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(medicalrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediaclReNumJLab)
                    .addComponent(alergy3JLab)
                    .addComponent(alergy2Lab)
                    .addComponent(alergy1JLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(medicalrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicalRecNumJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alergy1JTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alergy2JTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alergy3JTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        medicalrecordLayout.setVerticalGroup(
            medicalrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicalrecordLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(medicalrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(medicalrecordLayout.createSequentialGroup()
                        .addGroup(medicalrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mediaclReNumJLab)
                            .addComponent(medicalRecNumJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alergy1JLab))
                    .addComponent(alergy1JTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(medicalrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergy2JTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alergy2Lab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(medicalrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergy3JLab)
                    .addComponent(alergy3JTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButton1.setText("SUBMIT&NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(medicalrecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(medicalrecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(type == 2){
            JOptionPane.showMessageDialog(null,"You Cannot Change Information");
            
        }else{
        MedicalRecord medicalRecord = new MedicalRecord();
        medicalRecord.setMedicalRecordNum(medicalRecNumJTF.getText());
        medicalRecord.setAlergy1(alergy1JTF.getText());
        medicalRecord.setAlergy2(alergy2JTF.getText());
        medicalRecord.setAlergy3(alergy3JTF.getText());
        person.setMedicalRecord(medicalRecord);
        
        

        JOptionPane.showMessageDialog(null, "Create Medical Information successfully","warning", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alergy1JLab;
    private javax.swing.JTextField alergy1JTF;
    private javax.swing.JTextField alergy2JTF;
    private javax.swing.JLabel alergy2Lab;
    private javax.swing.JLabel alergy3JLab;
    private javax.swing.JTextField alergy3JTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel mediaclReNumJLab;
    private javax.swing.JTextField medicalRecNumJTF;
    private javax.swing.JPanel medicalrecord;
    // End of variables declaration//GEN-END:variables
}
